import {ReactNode} from "react";
import type {Metadata} from 'next'
import Header from "components/Header";
import Footer from "components/Footer";
import 'styles/global.scss'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children}: {
    children: ReactNode
}) {
    return (
        <html lang="en">
            <body>
                <Header />
                {children}
                <Footer />
            </body>
        </html>
    )
}
