import { ReactNode } from 'react';
import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import Header from 'components/Header';
import Footer from 'components/Footer';
import { isValidLocale } from 'utils/locales';
import { roboto, signika } from '@/fonts';
import 'styles/global.scss';
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const locales: Locales = ['en', 'ru', 'hy'];

export default function RootLayout({
  children,
  params: { locale },
}: {
  children: ReactNode;
  params: { locale: string };
}) {
  if (!isValidLocale(locales, locale)) notFound();

  return (
    <html lang={locale} className={`${roboto.variable} ${signika.variable}`}>
      <body>
        <Header />
        <main>
          <div className='container'>{children}</div>
        </main>
        <Footer />
      </body>
    </html>
  );
}
